### ISSUE TITLE
Unable to import from 'interface-forge'

### ISSUE THREAD

**Issue by cjsilva-umich** [Goldziher/interface-forge#22]
I'm trying to follow along with the basic example, but something seems to be not working about the install of interface forge.

I followed by using 'yarn install --dev interface-forge' and go to create a factory, but I get an error on the line:
`import { TypeFactory } from 'interface-forge'`

> Cannot find module 'interface-forge' or its corresponding type declarations.ts(2307)

I even tried to recreate the basic example in a codesandbox, but it gives the same error:
https://codesandbox.io/s/gallant-curran-xc7cvq?file=/src/features/factories.ts

Is there a current breaking change in the published library or am I missing something to get this working?

**Comment by cjsilva-umich** [comment]
However, doing so results in the following errors when doing so with my create-react-app project:
```
ERROR in ./node_modules/interface-forge/dist/utils/file.js 16:29-42
Module not found: Error: Can't resolve 'fs' in '/Users/cjsilva/Documents/SIMPL/i18n-redux-ts/node_modules/interface-forge/dist/utils'

ERROR in ./node_modules/interface-forge/dist/utils/file.js 18:31-46
Module not found: Error: Can't resolve 'path' in '/Users/cjsilva/Documents/SIMPL/i18n-redux-ts/node_modules/interface-forge/dist/utils'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }
```

**Comment by Goldziher** [comment]
Oh my bad. Rollup apparently changed stuff. I'll fix this today 🙃

**Comment by cjsilva-umich** [comment]
I think it would be helpful to be able to use it for testing using mocked data on the front end. If you have a better usage pattern, however, that would let me test the data created with interface-forge on the front end, I'd be happy to hear how to use it in a more recommended way.

**Comment by dkress59** [comment]
So, these are two separate issues:
1. cannot import from 'interface-forge': I just upgraded to v1.5.0 in one of my projects, there I have the same problem – I am using Yarn PnP, so it's probably a compatibility issue with pnpm
2. cannot use TypeFactory in the browser: I'm almost sure this was possible at one point, but maybe that was before we brought in FixtureFactory – I agree, it would be super useful to use TypeFactory in the browser to develop against mock data

We'll probably need to fix 1. before looking at 2., but I'll see what I can do!

**Comment by dkress59** [comment]
> I read through the linked SO post before asking here, and the general consensus seems to be "don't do it". At least, I couldn't find an approach that was widely accepted as the proper way to do this.

@cjsilva-umich The reason why it is not recommended is, that functions which rely on the shimmed core modules will break. The two NodeJS core modules required by interface-forge, `fs` and `path` are only used by the  `FixtureFactory` class, but nowhere else. This means that you are pretty much on the safe side, if you only use the `TypeFactory` class in the browser, having shimmed the two core modules in your webpack config like this:

```typescript
			resolve: {
				…,
				fallback: {
					fs: false,
					path: false,
				},
			},
```

The only culprit would be, that if in the future you installed other packages intended for NodeJS, which rely on `fs` or `path`, and you used them in the browser, you would not get an error message from the webpack compiler – the code simply wouldn't run properly, or a different kind of error would be thrown.

So with the resolve.fallback snippet from above in your webpack config and v1.4.7 of interface-forge, you should be good to go!
I will still look into including a shim/polyfill for browser-usage and/or include this issue in the docs.
